import { useEffect, useState } from 'react';
import { apiFetch } from '../../lib/api';

type Cohort = { cohort?: string; month?: string; size?: number; retention?: number[]; retentionRates?: number[] };
type Data = { churnRate: number; retentionRate: number; activeCustomers: number; churnedCustomers: number; atRiskCustomers: number; totalCustomers: number; monthlyCohorts?: Cohort[]; cohortRetention?: Cohort[] };
type Props = { startDate?: string; endDate?: string };

export default function ChurnRateDisplay({ startDate, endDate }: Props) {
    const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(''); const [periodDays, setPeriodDays] = useState(90);
    useEffect(() => { const p = new URLSearchParams({ periodDays: String(periodDays) }); if (startDate) p.set('startDate', startDate); if (endDate) p.set('endDate', endDate); Promise.resolve().then(() => { setData(null); setError(''); return apiFetch<{ data: Data }>(`/analytics/churn-rate?${p}`); }).then(r => setData(r.data)).catch(() => setError('Retensi pelanggan gagal dimuat.')); }, [periodDays, startDate, endDate]);
    if (error) return <div role="alert" className="p-6 bg-white border border-red-200 rounded-xl text-red-700">{error}</div>;
    if (!data) return <div className="p-10 bg-white border border-zinc-200 rounded-xl text-center text-zinc-500">Memuat retensi…</div>;
    const cohorts = data.monthlyCohorts ?? data.cohortRetention ?? [];
    const maxMonths = Math.max(0, ...cohorts.map(c => (c.retention ?? c.retentionRates ?? []).length));
    return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Retensi & Churn</h2><p className="text-sm text-zinc-500">Snapshot churn bersifat deskriptif, bukan bukti sebab-akibat.</p></div><label className="text-sm font-medium">Ambang tidak aktif<select value={periodDays} onChange={e => setPeriodDays(Number(e.target.value))} className="ml-2 border border-zinc-300 rounded-lg p-2" aria-label="Ambang hari tidak aktif"><option value={60}>60 hari</option><option value={90}>90 hari</option><option value={120}>120 hari</option></select></label></div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[['Retensi snapshot', `${data.retentionRate.toFixed(1)}%`], ['Churn snapshot', `${data.churnRate.toFixed(1)}%`], ['Pelanggan aktif', data.activeCustomers], ['Perlu perhatian', data.atRiskCustomers]].map(([label, value]) => <article key={label} className="bg-white border border-zinc-200 rounded-xl p-4"><p className="text-sm text-zinc-500">{label}</p><p className="text-2xl font-black mt-1">{value}</p></article>)}</div>
        <div className="bg-white border border-zinc-200 rounded-xl p-5 overflow-x-auto"><h3 className="font-bold">Retensi cohort bulanan</h3><p className="text-xs text-zinc-500 mb-4">Persentase pelanggan cohort yang kembali pada bulan berikutnya.</p>{cohorts.length ? <table className="text-xs min-w-max"><thead><tr><th scope="col" className="p-2 text-left">Cohort</th><th scope="col" className="p-2 text-right">Ukuran</th>{Array.from({ length: maxMonths }, (_, i) => <th scope="col" className="p-2 text-center" key={i}>B{i}</th>)}</tr></thead><tbody>{cohorts.map((cohort, i) => <tr key={`${cohort.cohort ?? cohort.month}-${i}`}><th scope="row" className="p-2 text-left font-medium">{cohort.cohort ?? cohort.month}</th><td className="p-2 text-right">{cohort.size ?? '—'}</td>{(cohort.retention ?? cohort.retentionRates ?? []).map((rate, j) => <td key={j} className="p-1"><span className="block rounded p-2 text-center border border-zinc-200" style={{ backgroundColor: `rgba(24,24,27,${Math.max(.05, rate / 100)})`, color: rate > 55 ? 'white' : '#18181b' }} aria-label={`Bulan ${j}: ${rate.toFixed(1)} persen`}>{rate.toFixed(0)}%</span></td>)}</tr>)}</tbody></table> : <p className="py-10 text-center text-zinc-500">Data cohort bulanan belum tersedia untuk periode ini.</p>}</div>
    </section>;
}
