import { useEffect, useState } from 'react';
import { apiFetch } from '../../lib/api';
type Cell = { day: string; dayIndex: number; hour: number; count: number; revenue: number }; type Data = { heatmap: Cell[]; peakHours: Cell[]; offPeakHours: Cell[] }; type Props = { startDate?: string; endDate?: string };
const money = (n: number) => new Intl.NumberFormat('id-ID', { notation: 'compact', style: 'currency', currency: 'IDR' }).format(n || 0);
export default function PeakHoursHeatmap({ startDate, endDate }: Props) { const [data,setData]=useState<Data|null>(null); const [error,setError]=useState('');
useEffect(()=>{const p=new URLSearchParams();if(startDate)p.set('startDate',startDate);if(endDate)p.set('endDate',endDate);setData(null);setError('');apiFetch<{data:Data}>(`/analytics/peak-hours?${p}`).then(r=>setData(r.data)).catch(()=>setError('Pola jam ramai gagal dimuat.'));},[startDate,endDate]);
if(error)return <div role="alert" className="p-6 bg-white border rounded-xl text-red-700">{error}</div>; if(!data)return <div className="p-10 bg-white border rounded-xl text-center text-zinc-500">Memuat jam ramai…</div>;
const hours=[...new Set(data.heatmap.map(x=>x.hour))].sort((a,b)=>a-b), days=[...new Set(data.heatmap.map(x=>x.day))]; const max=Math.max(1,...data.heatmap.map(x=>x.count));
return <section className="bg-white border border-zinc-200 rounded-xl p-5 overflow-x-auto"><h2 className="font-bold text-xl">Pola Transaksi per Jam</h2><p className="text-sm text-zinc-500 mb-4">Intensitas berdasarkan jumlah transaksi; detail menampilkan pendapatan.</p><div className="min-w-max grid gap-1" style={{gridTemplateColumns:`6rem repeat(${hours.length}, 2.5rem)`}}><div />{hours.map(h=><div key={h} className="text-xs text-center">{h}:00</div>)}{days.map(day=><div key={day} className="contents"><div className="text-sm p-2">{day}</div>{hours.map(hour=>{const c=data.heatmap.find(x=>x.day===day&&x.hour===hour);return <div key={hour} title={c?`${c.count} transaksi · ${money(c.revenue)}`:'0 transaksi'} aria-label={c?`${day} pukul ${hour}, ${c.count} transaksi, pendapatan ${money(c.revenue)}`:`${day} pukul ${hour}, 0 transaksi`} className="h-10 rounded border border-zinc-200" style={{backgroundColor:`rgba(24,24,27,${c?Math.max(.06,c.count/max):.02})`}} />})}</div>)}</div><div className="mt-4 flex gap-4 text-xs text-zinc-600"><span>Label utama: jumlah transaksi</span><span>Detail: pendapatan</span></div></section> }
