version: '3.9'

services:
  frontend:
    container_name: staycool-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7781:80"
    environment:
      - TZ=Asia/Jakarta
