ALTER TABLE `BookingConfig`
  ADD COLUMN `address` VARCHAR(191) NULL,
  ADD COLUMN `whatsappNumber` VARCHAR(191) NULL,
  ADD COLUMN `mapsUrl` VARCHAR(191) NULL,
  ADD COLUMN `instagramUrl` VARCHAR(191) NULL,
  ADD COLUMN `bookingDaysAhead` INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN `regularOpenHour` INTEGER NOT NULL DEFAULT 11,
  ADD COLUMN `fridayOpenHour` INTEGER NOT NULL DEFAULT 13,
  ADD COLUMN `closeHour` INTEGER NOT NULL DEFAULT 22,
  ADD COLUMN `headBarberId` INTEGER NULL;
